package com.retailco.bankrag.security;

import java.math.BigDecimal;
import java.util.List;

/**
 * Deliverable: "Tool-calling integration module." L2 HLD UseCase3
 * Implementation Approach, steps 1-5, all live in this one class's public
 * methods:
 *   1. Authenticate request using token validation.       (verifyAndAuthorize)
 *   2. Determine if tool calling is required.               (IntentClassifier, separate class)
 *   3. Call backend banking service.                        (this class's methods)
 *   4. Fetch data from a relational database.                (BankingDataStore)
 *   5. Mask sensitive fields before response.                (PiiMasking, applied before returning)
 *
 * Each public method here is one "tool" an LLM-based agent (e.g. L2/UC2's
 * RagAssistant, extended) would function-call when a user's query needs
 * live account data rather than policy-document retrieval -- see
 * tool-calling/tool-calling-design.md for how intent routing between UC2's
 * RAG pipeline and this class's tools is meant to work end-to-end.
 *
 * "Information must be retrieved securely and not generated by the AI
 * model" (L2 HLD UseCase3 Business Context) is enforced structurally: no
 * method here ever routes through an LlmClient -- every value returned
 * comes directly from BankingDataStore, with PiiMasking applied before the
 * result leaves this class. There is no code path by which a generative
 * model could fabricate a balance or transaction.
 */
public class BankingToolService {

    private final JwtService jwtService;
    private final BankingDataStore dataStore;

    public BankingToolService(JwtService jwtService, BankingDataStore dataStore) {
        this.jwtService = jwtService;
        this.dataStore = dataStore;
    }

    public record MaskedAccount(String accountNumberMasked, String accountType, BigDecimal balance, String currency) {
    }

    public record MaskedTransaction(String transactionId, String date, String description, BigDecimal amount, String type) {
    }

    public record MaskedLoan(String loanId, String loanType, BigDecimal principal, BigDecimal outstanding, BigDecimal interestRate) {
    }

    /**
     * Tool: get_account_balance. Returns every account belonging to the
     * authenticated customer, with account numbers masked (last 4 digits
     * visible only).
     */
    public List<MaskedAccount> getAccountBalance(String bearerToken, String requestedCustomerId) {
        JwtService.Claims claims = verifyAndAuthorize(bearerToken, requestedCustomerId);
        return dataStore.findAccountsByCustomerId(requestedCustomerId).stream()
                .map(a -> new MaskedAccount(PiiMasking.maskAccountNumber(a.accountNumber()),
                        a.accountType(), a.balance(), a.currency()))
                .toList();
    }

    /**
     * Tool: get_transaction_history. Requires the caller to already know
     * (or have been given, via get_account_balance) the specific account
     * number -- this method still re-verifies that account belongs to the
     * authenticated customer before returning anything, rather than
     * trusting the caller's claim that it does (defense in depth against a
     * client passing an account number that isn't actually theirs).
     */
    public List<MaskedTransaction> getTransactionHistory(String bearerToken, String requestedCustomerId,
                                                           String accountNumber, int limit) {
        JwtService.Claims claims = verifyAndAuthorize(bearerToken, requestedCustomerId);

        boolean accountBelongsToCustomer = dataStore.findAccountsByCustomerId(requestedCustomerId).stream()
                .anyMatch(a -> a.accountNumber().equals(accountNumber));
        if (!accountBelongsToCustomer) {
            throw new UnauthorizedException("Requested account does not belong to the authenticated customer");
        }

        return dataStore.findTransactionsByAccountNumber(accountNumber, limit).stream()
                .map(t -> new MaskedTransaction(t.transactionId(), t.date().toString(), t.description(), t.amount(), t.type()))
                .toList();
    }

    /** Tool: get_loan_outstanding. */
    public List<MaskedLoan> getLoanOutstanding(String bearerToken, String requestedCustomerId) {
        JwtService.Claims claims = verifyAndAuthorize(bearerToken, requestedCustomerId);
        return dataStore.findLoansByCustomerId(requestedCustomerId).stream()
                .map(l -> new MaskedLoan(l.loanId(), l.loanType(), l.principal(), l.outstanding(), l.interestRate()))
                .toList();
    }

    /**
     * Shared auth + authorization gate for every tool method: the token
     * must be structurally valid, cryptographically unforged, unexpired
     * (authentication -- JwtService.verify), AND its subject claim must
     * match the customer id the caller is asking about, unless the token
     * carries an ADMIN role (authorization -- checked here, not delegated
     * to JwtService, since "which customer can this token act on behalf
     * of" is a business rule, not a token-format concern).
     */
    private JwtService.Claims verifyAndAuthorize(String bearerToken, String requestedCustomerId) {
        JwtService.VerificationResult result = jwtService.verify(stripBearerPrefix(bearerToken));
        if (result instanceof JwtService.Invalid invalid) {
            throw new UnauthorizedException("Authentication failed: " + invalid.reason());
        }
        JwtService.Claims claims = ((JwtService.Valid) result).claims();

        boolean isSelf = claims.subject().equals(requestedCustomerId);
        boolean isAdmin = claims.roles().contains("ADMIN");
        if (!isSelf && !isAdmin) {
            throw new UnauthorizedException("Token subject '" + claims.subject()
                    + "' is not authorized to access customer '" + requestedCustomerId + "'");
        }
        return claims;
    }

    private String stripBearerPrefix(String header) {
        if (header != null && header.startsWith("Bearer ")) {
            return header.substring("Bearer ".length());
        }
        return header;
    }
}
