package com.retailco.bankrag.security;

import java.math.BigDecimal;
import java.util.List;

// CONCEPT: "Tool calling" -- the pattern of exposing a fixed set of safe,
// deterministic operations (here: get_account_balance,
// get_transaction_history, get_loan_outstanding) that an AI-assisted
// system can invoke for live data, instead of letting an LLM generate
// that data itself.
// PURPOSE: This is the ONE place live banking data leaves the system.
// Every public method here does the same three things in order: (1)
// authenticate + authorize the caller via verifyAndAuthorize(), (2) fetch
// raw data from BankingDataStore, (3) mask sensitive fields via PiiMasking
// before returning.
//
// WHY THIS IS SECURITY-CRITICAL: no method in this class ever calls an
// LlmClient. Every returned value traces directly back to
// BankingDataStore, with masking applied before it leaves this class --
// there is no code path by which a generative model could hallucinate or
// paraphrase a balance/transaction/loan figure. This structurally
// satisfies "live data must be retrieved securely, not generated by the
// AI model" -- it's not just a written rule, the code makes it impossible
// to violate.
//
// HOW verifyAndAuthorize() WORKS (the shared gate every method calls
// first): first AUTHENTICATE the token (is it a real, unexpired,
// correctly-signed JWT? -- delegated entirely to JwtService), then
// AUTHORIZE it (does this token's subject match the customer being asked
// about, or does it hold ADMIN?). Authentication answers "who are you?";
// authorization answers "are you allowed to see THIS customer's data?" --
// keeping them as two distinct steps (rather than one combined check)
// matches how JWT/RBAC security is conventionally reasoned about.
//
// IMPORTANT (defense in depth, see getTransactionHistory): even after a
// customer id is authorized, the method independently re-checks that the
// SPECIFIC account number requested actually belongs to that customer --
// never trusting a client-supplied account number just because the
// customer id check passed.
public class BankingToolService {

    private final JwtService jwtService;
    private final BankingDataStore dataStore;

    public BankingToolService(JwtService jwtService, BankingDataStore dataStore) {
        this.jwtService = jwtService;
        this.dataStore = dataStore;
    }

    public record MaskedAccount(String accountNumberMasked, String accountType, BigDecimal balance, String currency) {
    }

    public record MaskedTransaction(String transactionId, String date, String description, BigDecimal amount, String type) {
    }

    public record MaskedLoan(String loanId, String loanType, BigDecimal principal, BigDecimal outstanding, BigDecimal interestRate) {
    }

    /**
     * Tool: get_account_balance. Returns every account belonging to the
     * authenticated customer, with account numbers masked (last 4 digits
     * visible only).
     */
    public List<MaskedAccount> getAccountBalance(String bearerToken, String requestedCustomerId) {
        JwtService.Claims claims = verifyAndAuthorize(bearerToken, requestedCustomerId);
        return dataStore.findAccountsByCustomerId(requestedCustomerId).stream()
                .map(a -> new MaskedAccount(PiiMasking.maskAccountNumber(a.accountNumber()),
                        a.accountType(), a.balance(), a.currency()))
                .toList();
    }

    /**
     * Tool: get_transaction_history. Requires the caller to already know
     * (or have been given, via get_account_balance) the specific account
     * number -- this method still re-verifies that account belongs to the
     * authenticated customer before returning anything, rather than
     * trusting the caller's claim that it does (defense in depth against a
     * client passing an account number that isn't actually theirs).
     */
    public List<MaskedTransaction> getTransactionHistory(String bearerToken, String requestedCustomerId,
                                                           String accountNumber, int limit) {
        JwtService.Claims claims = verifyAndAuthorize(bearerToken, requestedCustomerId);

        boolean accountBelongsToCustomer = dataStore.findAccountsByCustomerId(requestedCustomerId).stream()
                .anyMatch(a -> a.accountNumber().equals(accountNumber));
        if (!accountBelongsToCustomer) {
            throw new UnauthorizedException("Requested account does not belong to the authenticated customer");
        }

        return dataStore.findTransactionsByAccountNumber(accountNumber, limit).stream()
                .map(t -> new MaskedTransaction(t.transactionId(), t.date().toString(), t.description(), t.amount(), t.type()))
                .toList();
    }

    /** Tool: get_loan_outstanding. */
    public List<MaskedLoan> getLoanOutstanding(String bearerToken, String requestedCustomerId) {
        JwtService.Claims claims = verifyAndAuthorize(bearerToken, requestedCustomerId);
        return dataStore.findLoansByCustomerId(requestedCustomerId).stream()
                .map(l -> new MaskedLoan(l.loanId(), l.loanType(), l.principal(), l.outstanding(), l.interestRate()))
                .toList();
    }

    /**
     * Shared auth + authorization gate for every tool method: the token
     * must be structurally valid, cryptographically unforged, unexpired
     * (authentication -- JwtService.verify), AND its subject claim must
     * match the customer id the caller is asking about, unless the token
     * carries an ADMIN role (authorization -- checked here, not delegated
     * to JwtService, since "which customer can this token act on behalf
     * of" is a business rule, not a token-format concern).
     */
    private JwtService.Claims verifyAndAuthorize(String bearerToken, String requestedCustomerId) {
        JwtService.VerificationResult result = jwtService.verify(stripBearerPrefix(bearerToken));
        if (result instanceof JwtService.Invalid invalid) {
            throw new UnauthorizedException("Authentication failed: " + invalid.reason());
        }
        JwtService.Claims claims = ((JwtService.Valid) result).claims();

        boolean isSelf = claims.subject().equals(requestedCustomerId);
        boolean isAdmin = claims.roles().contains("ADMIN");
        if (!isSelf && !isAdmin) {
            throw new UnauthorizedException("Token subject '" + claims.subject()
                    + "' is not authorized to access customer '" + requestedCustomerId + "'");
        }
        return claims;
    }

    private String stripBearerPrefix(String header) {
        if (header != null && header.startsWith("Bearer ")) {
            return header.substring("Bearer ".length());
        }
        return header;
    }
}
