package com.retailco.bankrag.security;

import java.util.List;
import java.util.regex.Pattern;

/**
 * Deliverable: "Tool calling logic" (the routing half; BankingToolService is
 * the execution half). L2 HLD UseCase3 Implementation Approach step 2:
 * "Determine if tool calling is required."
 *
 * Decides whether a user's query is a POLICY question (route to L2/UC2's
 * RagAssistant, which retrieves from documents and must never fabricate
 * live account data) or a LIVE_DATA question (route to this use case's
 * BankingToolService, which must never go through an LLM at all). This is
 * the concrete mechanism behind L2 HLD UseCase1/UseCase3's shared
 * requirement that live banking data "must be retrieved securely and not
 * generated by the AI model" -- routing happens BEFORE any LLM call, so a
 * live-data query never reaches a prompt/generation step where a model
 * could hallucinate a balance.
 *
 * Keyword/pattern-based, same disclosed-heuristic approach as L2/UC2's
 * PromptInjectionGuard/UnsafeQueryGuard (a production system would likely
 * use an LLM function-calling/tool-selection step instead, but that
 * requires a reachable LLM API this sandbox doesn't have -- see
 * tool-calling/tool-calling-design.md for the swap-in path).
 */
public final class IntentClassifier {

    public enum Intent { POLICY_QUESTION, ACCOUNT_BALANCE, TRANSACTION_HISTORY, LOAN_OUTSTANDING, AMBIGUOUS }

    private static final List<Pattern> BALANCE_PATTERNS = List.of(
            Pattern.compile("account balance|my balance|how much (money |)do i have|current balance", Pattern.CASE_INSENSITIVE)
    );
    private static final List<Pattern> TRANSACTION_PATTERNS = List.of(
            Pattern.compile("transaction history|recent transactions|my (recent |)transactions|statement of account|last \\d+ transactions", Pattern.CASE_INSENSITIVE)
    );
    private static final List<Pattern> LOAN_PATTERNS = List.of(
            Pattern.compile("loan outstanding|outstanding (loan |)amount|how much (do i owe|is left) on my loan|remaining loan balance", Pattern.CASE_INSENSITIVE)
    );

    public Intent classify(String query) {
        boolean matchesBalance = matchesAny(query, BALANCE_PATTERNS);
        boolean matchesTransaction = matchesAny(query, TRANSACTION_PATTERNS);
        boolean matchesLoan = matchesAny(query, LOAN_PATTERNS);

        int matchCount = (matchesBalance ? 1 : 0) + (matchesTransaction ? 1 : 0) + (matchesLoan ? 1 : 0);
        if (matchCount > 1) {
            // A query matching more than one live-data category is treated
            // as ambiguous rather than guessed at -- e.g. "show my balance
            // and loan outstanding" would need to be split into two tool
            // calls by a real orchestrating agent, not silently answered
            // with only one of them.
            return Intent.AMBIGUOUS;
        }
        if (matchesBalance) return Intent.ACCOUNT_BALANCE;
        if (matchesTransaction) return Intent.TRANSACTION_HISTORY;
        if (matchesLoan) return Intent.LOAN_OUTSTANDING;

        // Default: anything not matching a live-data pattern is treated as
        // a policy question and routed to retrieval (L2/UC1 & UC2), which
        // has its own guardrails (weak-retrieval fallback, unsafe-advice
        // guard) for queries that turn out not to be answerable there either.
        return Intent.POLICY_QUESTION;
    }

    private boolean matchesAny(String query, List<Pattern> patterns) {
        return patterns.stream().anyMatch(p -> p.matcher(query).find());
    }
}
