package com.retailco.bankrag.integration;

import com.retailco.bankrag.assistant.RagAssistant;
import com.retailco.bankrag.observability.ObservableRagAssistant;
import com.retailco.bankrag.security.BankingToolService;
import com.retailco.bankrag.security.IntentClassifier;
import com.retailco.bankrag.security.UnauthorizedException;

import java.util.List;

/**
 * This is the top-level class that ties everything together — intent
 * classification, the RAG assistant, and the secure banking tools — into
 * ONE unified API. If you want to understand how this whole module
 * works, this is the class to read first.
 * <p>
 * Given a raw question (plus login info, for questions that need live
 * data), it routes the question to the right place and returns one
 * consistent result type. See {@code handle()} below: first,
 * {@code IntentClassifier} figures out what kind of question this is.
 * A policy question goes to the RAG assistant, which searches company
 * documents and answers using an AI model. A question about account
 * balance, transaction history, or an outstanding loan goes straight to
 * {@code BankingToolService} instead, which checks the caller's login
 * token and returns real, masked data — never anything generated by an
 * AI model. An ambiguous question (mixing more than one of these) gets a
 * message asking the user to ask one thing at a time. This class doesn't
 * contain any new business logic of its own — everything it needs was
 * already built and tested in the pieces it calls; its only job is
 * routing between them and combining their results into one shape.
 * <p>
 * {@code UnifiedResponse} is a Java "sealed interface": it can ONLY ever
 * be one of four things — {@code PolicyAnswer}, {@code LiveDataAnswer},
 * {@code AccessDenied}, or {@code Ambiguous}. The compiler enforces this,
 * which is why the {@code switch} inside {@code handle()} doesn't need a
 * catch-all {@code default} branch — if a new kind of question were ever
 * added without updating this switch, the code simply wouldn't compile,
 * instead of silently doing the wrong thing at runtime.
 * <p>
 * One more thing worth noticing: if {@code BankingToolService} throws an
 * {@code UnauthorizedException}, it's caught right here and turned into
 * an {@code AccessDenied} result instead of being allowed to crash the
 * request — this way every possible outcome still comes back as a normal
 * {@code UnifiedResponse}, while still faithfully reporting that access
 * was denied.
 */
public class IntegratedBankingAssistant {

    private final IntentClassifier intentClassifier;
    private final ObservableRagAssistant observableRagAssistant;
    private final BankingToolService bankingToolService;

    public IntegratedBankingAssistant(IntentClassifier intentClassifier, ObservableRagAssistant observableRagAssistant,
                                       BankingToolService bankingToolService) {
        this.intentClassifier = intentClassifier;
        this.observableRagAssistant = observableRagAssistant;
        this.bankingToolService = bankingToolService;
    }

    public sealed interface UnifiedResponse permits PolicyAnswer, LiveDataAnswer, AccessDenied, Ambiguous {
    }

    public record PolicyAnswer(RagAssistant.AssistantResponse ragResponse, boolean servedFromCache) implements UnifiedResponse {
    }

    public record LiveDataAnswer(IntentClassifier.Intent intent, Object data) implements UnifiedResponse {
    }

    public record AccessDenied(String reason) implements UnifiedResponse {
    }

    public record Ambiguous(String message) implements UnifiedResponse {
    }

    /**
     * @param query              the raw user question
     * @param bearerToken        JWT bearer token (only consulted for LIVE_DATA intents; a policy
     *                           question never touches authentication, matching L2/UC2's design
     *                           where RagAssistant has no auth dependency at all)
     * @param requestedCustomerId the customerId the caller is asking about (only relevant for LIVE_DATA intents)
     * @param accountNumber      only required for TRANSACTION_HISTORY; ignored otherwise
     */
    public UnifiedResponse handle(String query, String bearerToken, String requestedCustomerId, String accountNumber) {
        IntentClassifier.Intent intent = intentClassifier.classify(query);

        return switch (intent) {
            case POLICY_QUESTION -> {
                ObservableRagAssistant.ObservedResponse observed = observableRagAssistant.ask(query);
                yield new PolicyAnswer(observed.response(), observed.servedFromCache());
            }
            case ACCOUNT_BALANCE -> {
                try {
                    List<BankingToolService.MaskedAccount> accounts =
                            bankingToolService.getAccountBalance(bearerToken, requestedCustomerId);
                    yield new LiveDataAnswer(intent, accounts);
                } catch (UnauthorizedException e) {
                    yield new AccessDenied(e.getMessage());
                }
            }
            case TRANSACTION_HISTORY -> {
                try {
                    List<BankingToolService.MaskedTransaction> transactions =
                            bankingToolService.getTransactionHistory(bearerToken, requestedCustomerId, accountNumber, 10);
                    yield new LiveDataAnswer(intent, transactions);
                } catch (UnauthorizedException e) {
                    yield new AccessDenied(e.getMessage());
                }
            }
            case LOAN_OUTSTANDING -> {
                try {
                    List<BankingToolService.MaskedLoan> loans =
                            bankingToolService.getLoanOutstanding(bearerToken, requestedCustomerId);
                    yield new LiveDataAnswer(intent, loans);
                } catch (UnauthorizedException e) {
                    yield new AccessDenied(e.getMessage());
                }
            }
            case AMBIGUOUS -> new Ambiguous(
                    "This question seems to combine more than one type of request. "
                            + "Please ask about your account balance, transactions, loan outstanding, "
                            + "or a policy question separately.");
        };
    }
}
