package com.retailco.bankrag.security;

import com.retailco.bankrag.logging.StructuredAuditLogger;
import com.retailco.bankrag.logging.StructuredAuditLogger.AuditEvent;

import java.math.BigDecimal;
import java.util.List;
import java.util.UUID;

/**
 * Deliverable: "Tool-calling integration module." L2 HLD UseCase3
 * Implementation Approach, steps 1-5, all live in this one class's public
 * methods:
 *   1. Authenticate request using token validation.       (verifyAndAuthorize)
 *   2. Determine if tool calling is required.               (IntentClassifier, separate class)
 *   3. Call backend banking service.                        (this class's methods)
 *   4. Fetch data from a relational database.                (BankingDataStore)
 *   5. Mask sensitive fields before response.                (PiiMasking, applied before returning)
 *
 * Each public method here is one "tool" an LLM-based agent (e.g. L2/UC2's
 * RagAssistant, extended) would function-call when a user's query needs
 * live account data rather than policy-document retrieval -- see
 * tool-calling/tool-calling-design.md for how intent routing between UC2's
 * RAG pipeline and this class's tools is meant to work end-to-end.
 *
 * "Information must be retrieved securely and not generated by the AI
 * model" (L2 HLD UseCase3 Business Context) is enforced structurally: no
 * method here ever routes through an LlmClient -- every value returned
 * comes directly from BankingDataStore, with PiiMasking applied before the
 * result leaves this class. There is no code path by which a generative
 * model could fabricate a balance or transaction.
 */
public class BankingToolService {

    private final JwtService jwtService;
    private final BankingDataStore dataStore;
    private final StructuredAuditLogger auditLogger;

    public BankingToolService(JwtService jwtService, BankingDataStore dataStore) {
        this(jwtService, dataStore, null);
    }

    /**
     * L2 HLD UseCase6 constructor: wires in the structured audit trail
     * (docs/secure-backend-integration-design.md's "every access decision is
     * logged" requirement). {@code auditLogger} is nullable so every UC3/UC5
     * call site that predates this use case keeps compiling and running
     * unchanged -- RBAC enforcement below does not depend on logging being
     * configured.
     */
    public BankingToolService(JwtService jwtService, BankingDataStore dataStore, StructuredAuditLogger auditLogger) {
        this.jwtService = jwtService;
        this.dataStore = dataStore;
        this.auditLogger = auditLogger;
    }

    public record MaskedAccount(String accountNumberMasked, String accountType, BigDecimal balance, String currency) {
    }

    public record MaskedTransaction(String transactionId, String date, String description, BigDecimal amount, String type) {
    }

    public record MaskedLoan(String loanId, String loanType, BigDecimal principal, BigDecimal outstanding, BigDecimal interestRate) {
    }

    /**
     * Tool: get_account_balance. Returns every account belonging to the
     * authenticated customer, with account numbers masked (last 4 digits
     * visible only).
     */
    public List<MaskedAccount> getAccountBalance(String bearerToken, String requestedCustomerId) {
        JwtService.Claims claims = verifyAndAuthorize(bearerToken, requestedCustomerId, "get_account_balance");
        return dataStore.findAccountsByCustomerId(requestedCustomerId).stream()
                .map(a -> new MaskedAccount(PiiMasking.maskAccountNumber(a.accountNumber()),
                        a.accountType(), a.balance(), a.currency()))
                .toList();
    }

    /**
     * Tool: get_transaction_history. Requires the caller to already know
     * (or have been given, via get_account_balance) the specific account
     * number -- this method still re-verifies that account belongs to the
     * authenticated customer before returning anything, rather than
     * trusting the caller's claim that it does (defense in depth against a
     * client passing an account number that isn't actually theirs).
     */
    public List<MaskedTransaction> getTransactionHistory(String bearerToken, String requestedCustomerId,
                                                           String accountNumber, int limit) {
        JwtService.Claims claims = verifyAndAuthorize(bearerToken, requestedCustomerId, "get_transaction_history");

        boolean accountBelongsToCustomer = dataStore.findAccountsByCustomerId(requestedCustomerId).stream()
                .anyMatch(a -> a.accountNumber().equals(accountNumber));
        if (!accountBelongsToCustomer) {
            throw new UnauthorizedException("Requested account does not belong to the authenticated customer");
        }

        return dataStore.findTransactionsByAccountNumber(accountNumber, limit).stream()
                .map(t -> new MaskedTransaction(t.transactionId(), t.date().toString(), t.description(), t.amount(), t.type()))
                .toList();
    }

    /** Tool: get_loan_outstanding. */
    public List<MaskedLoan> getLoanOutstanding(String bearerToken, String requestedCustomerId) {
        JwtService.Claims claims = verifyAndAuthorize(bearerToken, requestedCustomerId, "get_loan_outstanding");
        return dataStore.findLoansByCustomerId(requestedCustomerId).stream()
                .map(l -> new MaskedLoan(l.loanId(), l.loanType(), l.principal(), l.outstanding(), l.interestRate()))
                .toList();
    }

    /**
     * Shared auth + authorization gate for every tool method: the token
     * must be structurally valid, cryptographically unforged, unexpired
     * (authentication -- JwtService.verify), AND its subject claim must
     * match the customer id the caller is asking about, unless the token
     * carries an ADMIN role (authorization -- checked here, not delegated
     * to JwtService, since "which customer can this token act on behalf
     * of" is a business rule, not a token-format concern).
     */
    private JwtService.Claims verifyAndAuthorize(String bearerToken, String requestedCustomerId, String tool) {
        String correlationId = UUID.randomUUID().toString();
        JwtService.VerificationResult result = jwtService.verify(stripBearerPrefix(bearerToken));
        if (result instanceof JwtService.Invalid invalid) {
            audit(correlationId, "unknown", List.of(), requestedCustomerId, tool, "DENIED_AUTHENTICATION",
                    "Authentication failed: " + invalid.reason());
            throw new UnauthorizedException("Authentication failed: " + invalid.reason());
        }
        JwtService.Claims claims = ((JwtService.Valid) result).claims();

        // L2 HLD UseCase6 RBAC: the authorization decision itself now lives
        // in AccessPolicy (independently unit-tested), not inline here --
        // this method's remaining job is auth (token validity) + emitting
        // the structured audit record, same split UC3 already had between
        // JwtService (authn) and this method (authz), just with authz's
        // logic extracted one level further.
        AccessPolicy.Decision decision = AccessPolicy.evaluate(claims.subject(), claims.roles(), requestedCustomerId);
        if (decision instanceof AccessPolicy.Denied denied) {
            audit(correlationId, claims.subject(), claims.roles(), requestedCustomerId, tool, "DENIED_AUTHORIZATION", denied.reason());
            throw new UnauthorizedException(denied.reason());
        }
        AccessPolicy.Allowed allowed = (AccessPolicy.Allowed) decision;
        audit(correlationId, claims.subject(), claims.roles(), requestedCustomerId, tool,
                allowed.elevated() ? "ALLOWED_ELEVATED" : "ALLOWED_SELF", allowed.reason());
        return claims;
    }

    private void audit(String correlationId, String actorSubject, List<String> actorRoles,
                        String requestedCustomerId, String tool, String decision, String reason) {
        if (auditLogger == null) return; // logging is an add-on (UC6); RBAC enforcement above never depends on it
        auditLogger.log(new AuditEvent(correlationId, "banking_tool_access", actorSubject, actorRoles,
                requestedCustomerId, tool, decision, reason));
    }

    private String stripBearerPrefix(String header) {
        if (header != null && header.startsWith("Bearer ")) {
            return header.substring("Bearer ".length());
        }
        return header;
    }
}
